### ISSUE TITLE
Registering a custom protocol handler crashes

### ISSUE THREAD

**Issue by Mossop** [brave/electron#66]
* Electron version: 1.4.0
* Operating system: Windows

In Tofino we register a tofino:// protocol handler through the protocol.registerHttpProtocol electron API. This works in regular Electron but crashes with a segmentation fault in current builds of `brave/electron`.

**Comment by bridiver** [comment]
which brave electron version? It may be this
https://github.com/brave/electron/commit/082272de32166f23f36e4bebb0aefc538cf07246

**Comment by bridiver** [comment]
it broke after https://github.com/electron/electron/commit/e5daf63b0ee60098d43de281260743b41985fda4
and was fixed in the commit above

**Comment by Mossop** [comment]
I just retested with current master, v1.4.8 and still see the issue. I've been trying to bisect but it looks like you rebase for each new Electron version which makes bisecting more difficult.

**Comment by bridiver** [comment]
Interesting. We also register custom protocol handlers, but we're using `navigator.registerProtocolHandler` so I guess it's possible that the electron api still has a problem with our changes

**Comment by bridiver** [comment]
on the rebase issue, we have been the only people using our fork so far afaik and rebasing made things easier for us, but we're trying to move our changes from atom -> brave and upstream some changes to make it easier to extend
